import Head from 'next/head'

export default function GlobalHead() {
    return (
        <Head>
            <title>Replica</title>
            <meta name="description" content="Generated by hansol"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
    )
}